version: "3.8"

services:
  rancher:
    image: rancher/rancher:stable
    restart: always
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
    volumes:
      - rancher-data:/var/lib/rancher
    privileged: true 

volumes:
  rancher-data: 
