---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-image-renderer
  namespace: monitoring
data:
  GF_RENDERING_SERVER_URL: http://grafana-image-renderer.monitoring.svc:8081/render
  GF_RENDERING_CALLBACK_URL: http://prometheus-community-grafana.monitoring.svc:3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-image-renderer
  namespace: monitoring
  labels:
    app: grafana-image-renderer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-image-renderer
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: grafana-image-renderer
    spec:
      containers:
      - image: grafana/grafana-image-renderer
        name: grafana-image-renderer
        ports:
        - containerPort: 8081
          name: http
        env: 
        - name: IGNORE_HTTPS_ERRORS
          value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-image-renderer
  namespace: monitoring
spec:
  ports:
  - port: 8081
    targetPort: http
  selector:
    app: grafana-image-renderer
  type: ClusterIP